dist: bionic

before_install:
  - sudo apt update --quiet --quiet
  - sudo apt install --quiet --quiet python3-pip python3-setuptools
  - pip3 install --quiet --upgrade --user pip

script:
  - bundle exec jekyll build
  - pip3 install --quiet --upgrade --user git+https://github.com/DanielOaks/yamltypes.git@irc-defs-fixes#egg=yamltypes
  - ~/.local/bin/yamlvalidate $(find _data | grep \.yaml | grep -v "validation/" | xargs) --path _data/validation

notifications:
  email: false

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

git:
  quiet: true

cache:
  bundler: true
